# Generated by Django 4.2.29 on 2026-03-03 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donnees', '0001_initial'),
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('lienImageConsommable', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('seuilStockFaible', models.IntegerField(blank=True, help_text='Seuil en dessous duquel le stock est considéré comme faible', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('documents', models.ManyToManyField(blank=True, help_text='Documents associés au consommable', to='donnees.document')),
            ],
            options={
                'verbose_name': 'Consommable',
                'verbose_name_plural': 'Consommables',
                'db_table': 'gimao_consommable',
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('estMobile', models.BooleanField(default=False)),
                ('adresse', models.ForeignKey(blank=True, help_text='Adresse du magasin', null=True, on_delete=django.db.models.deletion.CASCADE, to='donnees.adresse')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'db_table': 'gimao_magasin',
            },
        ),
        migrations.CreateModel(
            name='Stocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.consommable')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.magasin')),
            ],
            options={
                'verbose_name': 'Stock en magasin',
                'verbose_name_plural': 'Stocks en magasin',
                'db_table': 'gimao_stocker',
                'unique_together': {('consommable', 'magasin')},
            },
        ),
        migrations.AddField(
            model_name='consommable',
            name='magasins',
            field=models.ManyToManyField(blank=True, related_name='consommables', through='stock.Stocker', to='stock.magasin'),
        ),
        migrations.CreateModel(
            name='PorterSur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_reference_prix', models.DateTimeField()),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournitures', to='stock.consommable')),
                ('fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournitures', to='donnees.fabricant')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournitures', to='donnees.fournisseur')),
            ],
            options={
                'verbose_name': 'Fourniture de consommable',
                'verbose_name_plural': 'Fournitures de consommables',
                'db_table': 'gimao_porter_sur',
                'unique_together': {('consommable', 'fournisseur', 'fabricant', 'date_reference_prix')},
            },
        ),
        migrations.CreateModel(
            name='EstCompatible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.consommable')),
                ('modeleEquipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipement.modeleequipement')),
            ],
            options={
                'verbose_name': 'Compatibilité consommable-modèle',
                'verbose_name_plural': 'Compatibilités consommable-modèle',
                'db_table': 'gimao_estcompatible',
                'unique_together': {('consommable', 'modeleEquipement')},
            },
        ),
    ]
