# Generated by Django 4.2.29 on 2026-06-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_consommable_archive_magasin_archive'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consommable',
            index=models.Index(fields=['archive', 'designation', 'id'], name='cons_arch_des_idx'),
        ),
        migrations.AddIndex(
            model_name='consommable',
            index=models.Index(fields=['archive', 'seuilStockFaible', 'id'], name='cons_arch_seuil_idx'),
        ),
        migrations.AddIndex(
            model_name='stocker',
            index=models.Index(fields=['magasin', 'consommable'], name='stock_mag_cons_idx'),
        ),
    ]
