# Generated by Django 4.2.29 on 2026-03-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPermission', models.CharField(help_text='Nom de la permission (ex: ajouter_utilisateur, supprimer_equipement)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la permission', null=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'gimao_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRole', models.CharField(help_text='Nom du rôle (ex: Administrateur, Technicien, etc.)', max_length=50)),
                ('rang', models.PositiveSmallIntegerField(help_text='Rang du rôle pour hiérarchiser les permissions (plus petit = plus élevé)')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'gimao_role',
                'ordering': ['rang'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(help_text='Identifiant unique pour la connexion', max_length=50, unique=True)),
                ('motDePasse', models.CharField(blank=True, help_text="Mot de passe hashé de l'utilisateur (null si pas encore défini)", max_length=128, null=True)),
                ('prenom', models.CharField(help_text="Prénom de l'utilisateur", max_length=50)),
                ('nomFamille', models.CharField(help_text="Nom de famille de l'utilisateur", max_length=50)),
                ('email', models.EmailField(help_text="Adresse email de l'utilisateur", max_length=150, unique=True)),
                ('photoProfil', models.FileField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='utilisateur_photos/')),
                ('derniereConnexion', models.DateTimeField(blank=True, help_text='Date et heure de la dernière connexion', null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, help_text='Date de création du compte')),
                ('actif', models.BooleanField(default=True, help_text='Indique si le compte est actif')),
                ('role', models.ForeignKey(help_text="Rôle attribué à l'utilisateur", on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='utilisateur.role')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'gimao_utilisateur',
                'ordering': ['nomFamille', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(help_text='Permission attribuée au rôle', on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='utilisateur.permission')),
                ('role', models.ForeignKey(help_text='Rôle auquel la permission est attribuée', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='utilisateur.role')),
            ],
            options={
                'verbose_name': 'Rôle-Permission',
                'verbose_name_plural': 'Rôles-Permissions',
                'db_table': 'gimao_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(help_text='Permissions associées à ce rôle', related_name='roles', through='utilisateur.RolePermission', to='utilisateur.permission'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Type de log (ex: création, modification, suppression)', max_length=50)),
                ('nomTable', models.CharField(help_text="Nom de la table affectée par l'action", max_length=50)),
                ('idCible', models.JSONField(help_text="Identifiant(s) de l'objet modifié")),
                ('champsModifies', models.JSONField(help_text='Champs modifiés et leurs nouvelles valeurs')),
                ('date', models.DateTimeField(auto_now_add=True, help_text="Date et heure de l'action")),
                ('group', models.UUIDField(blank=True, editable=False, help_text='Identifiant unique du groupe de logs (lié à une requête)', null=True)),
                ('utilisateur', models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='utilisateur.utilisateur')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'gimao_log',
                'ordering': ['-date'],
            },
        ),
    ]
