# Generated by Django 4.2.29 on 2026-03-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(help_text="Permission accordée à l'utilisateur", on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_permissions', to='utilisateur.permission')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='permissions_personnalisees', to='utilisateur.utilisateur')),
            ],
            options={
                'verbose_name': 'Permission utilisateur',
                'verbose_name_plural': 'Permissions utilisateur',
                'db_table': 'gimao_utilisateur_permission',
                'unique_together': {('utilisateur', 'permission')},
            },
        ),
    ]
