# Generated by Django 4.2.29 on 2026-03-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_utilisateurpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='rang',
        ),
    ]
