# Generated by Django 4.2.29 on 2026-03-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_permission_type_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='parent',
        ),
    ]
