# Generated by Django 4.2.29 on 2026-03-27 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_remove_permission_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Permission prérequise : cocher cette permission coche aussi son parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='utilisateur.permission'),
        ),
    ]
