# Generated by Django 4.2.29 on 2026-05-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_permission_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code court du module (ex: di, bt, eq)', max_length=20, unique=True)),
                ('nom', models.CharField(help_text="Nom lisible du module (ex: Demandes d'intervention)", max_length=100)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'gimao_module',
                'ordering': ['nom'],
            },
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-date'], name='log_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['utilisateur', '-date'], name='log_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['nomTable', '-date'], name='log_table_date_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['nomRole'], name='role_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['nomFamille', 'prenom', 'id'], name='user_name_list_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['role', 'nomFamille', 'prenom', 'id'], name='user_role_list_idx'),
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module auquel appartient cette permission', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='utilisateur.module'),
        ),
    ]
