# Generated by Django 4.2.29 on 2026-05-04 08:29
# Modifié manuellement : gimao_module peut exister déjà (ancienne BDD) ou non (nouvelle BDD).
# Le SQL brut d'origine était écrit uniquement pour MySQL/MariaDB (AUTO_INCREMENT,
# information_schema.COLUMNS...), ce qui empêchait la création de la base de test
# (SQLite, utilisée par pytest-django). Chaque fonction ci-dessous exécute désormais
# le SQL adapté au moteur réellement utilisé (connection.vendor), sans changer le SQL
# exécuté sur MySQL/MariaDB (donc sans impact sur les bases existantes en production).

from django.db import migrations, models
import django.db.models.deletion


def create_module_table_if_missing(apps, schema_editor):
    """Crée la table gimao_module seulement si elle est absente (ancienne BDD)."""
    connection = schema_editor.connection
    if 'gimao_module' in connection.introspection.table_names():
        return

    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            cursor.execute("""
                CREATE TABLE gimao_module (
                    id   INTEGER      NOT NULL PRIMARY KEY AUTOINCREMENT,
                    code VARCHAR(20)  NOT NULL UNIQUE,
                    nom  VARCHAR(100) NOT NULL
                )
            """)
        else:
            cursor.execute("""
                CREATE TABLE gimao_module (
                    id   BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    code VARCHAR(20)  NOT NULL UNIQUE,
                    nom  VARCHAR(100) NOT NULL
                )
            """)


def drop_module_table_if_present(apps, schema_editor):
    connection = schema_editor.connection
    if 'gimao_module' in connection.introspection.table_names():
        with connection.cursor() as cursor:
            cursor.execute("DROP TABLE gimao_module")


def add_module_fk_if_missing(apps, schema_editor):
    """Ajoute module_id sur gimao_permission seulement si la colonne est absente."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, 'gimao_permission')
        }
    if 'module_id' in existing_columns:
        return

    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            # SQLite ne supporte pas l'ajout de contrainte FOREIGN KEY via ALTER TABLE ;
            # la colonne suffit ici, la relation est déjà modélisée côté Django
            # (state_operations) et SQLite n'impose pas les FK par défaut.
            cursor.execute("ALTER TABLE gimao_permission ADD COLUMN module_id INTEGER NULL")
        else:
            cursor.execute("""
                ALTER TABLE gimao_permission
                ADD COLUMN module_id BIGINT NULL,
                ADD CONSTRAINT fk_permission_module
                    FOREIGN KEY (module_id) REFERENCES gimao_module(id)
            """)


def remove_module_fk(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, 'gimao_permission')
        }
    if 'module_id' not in existing_columns:
        return

    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            cursor.execute("ALTER TABLE gimao_permission DROP COLUMN module_id")
        else:
            cursor.execute("""
                ALTER TABLE gimao_permission
                DROP FOREIGN KEY IF EXISTS fk_permission_module,
                DROP COLUMN IF EXISTS module_id
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_permission_parent'),
    ]

    operations = [
        # ── gimao_module existait déjà en BDD ──────────────────────────────────
        # On met à jour l'état interne de Django sans recréer la table.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Module',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(help_text='Code court du module (ex: di, bt, eq)', max_length=20, unique=True)),
                        ('nom', models.CharField(help_text="Nom lisible du module (ex: Demandes d'intervention)", max_length=100)),
                    ],
                    options={
                        'verbose_name': 'Module',
                        'verbose_name_plural': 'Modules',
                        'db_table': 'gimao_module',
                        'ordering': ['nom'],
                    },
                ),
            ],
            database_operations=[
                # No-op si la table existe déjà (ancienne BDD), la crée sinon (nouvelle BDD).
                migrations.RunPython(
                    create_module_table_if_missing,
                    reverse_code=drop_module_table_if_present,
                ),
            ],
        ),

        # ── Nouveaux index sur Log (jamais créés) ───────────────────────────────
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-date'], name='log_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['utilisateur', '-date'], name='log_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['nomTable', '-date'], name='log_table_date_idx'),
        ),

        # ── Index sur Role et Utilisateur — IF NOT EXISTS (peuvent déjà exister) ──
        migrations.RunSQL(
            sql=[
                "CREATE INDEX IF NOT EXISTS role_nom_idx ON gimao_role (nomRole)",
                "CREATE INDEX IF NOT EXISTS user_name_list_idx ON gimao_utilisateur (nomFamille, prenom, id)",
                "CREATE INDEX IF NOT EXISTS user_role_list_idx ON gimao_utilisateur (role_id, nomFamille, prenom, id)",
            ],
            reverse_sql=[
                # DROP INDEX ... ON table est la syntaxe MySQL/MariaDB (SQLite n'accepte pas
                # la clause ON, mais ce chemin ne s'exécute qu'en cas de retour arrière de
                # migration, non utilisé lors de la simple création d'une base de test).
                "DROP INDEX IF EXISTS role_nom_idx ON gimao_role",
                "DROP INDEX IF EXISTS user_name_list_idx ON gimao_utilisateur",
                "DROP INDEX IF EXISTS user_role_list_idx ON gimao_utilisateur",
            ],
        ),
        # Synchroniser uniquement l'état Django pour ces index
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='role',
                    index=models.Index(fields=['nomRole'], name='role_nom_idx'),
                ),
                migrations.AddIndex(
                    model_name='utilisateur',
                    index=models.Index(fields=['nomFamille', 'prenom', 'id'], name='user_name_list_idx'),
                ),
                migrations.AddIndex(
                    model_name='utilisateur',
                    index=models.Index(fields=['role', 'nomFamille', 'prenom', 'id'], name='user_role_list_idx'),
                ),
            ],
            database_operations=[],  # déjà gérés par le RunSQL IF NOT EXISTS ci-dessus
        ),

        # ── FK permission.module — ajout conditionnel via RunPython ─────────────
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='permission',
                    name='module',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Module auquel appartient cette permission',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='permissions',
                        to='utilisateur.module',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_module_fk_if_missing,
                    reverse_code=remove_module_fk,
                ),
            ],
        ),
    ]
