# Generated by Django 4.2.29 on 2026-05-04 08:29
# Modifié manuellement : gimao_module peut exister déjà (ancienne BDD) ou non (nouvelle BDD).
# CREATE TABLE IF NOT EXISTS gère les deux cas. SeparateDatabaseAndState synchronise l'état Django.

from django.db import migrations, models
import django.db.models.deletion


def add_module_fk_if_missing(apps, schema_editor):
    """Ajoute module_id sur gimao_permission seulement si la colonne est absente."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME   = 'gimao_permission'
              AND COLUMN_NAME  = 'module_id'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE gimao_permission
                ADD COLUMN module_id BIGINT NULL,
                ADD CONSTRAINT fk_permission_module
                    FOREIGN KEY (module_id) REFERENCES gimao_module(id)
            """)


def remove_module_fk(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE gimao_permission
            DROP FOREIGN KEY IF EXISTS fk_permission_module,
            DROP COLUMN IF EXISTS module_id
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_permission_parent'),
    ]

    operations = [
        # ── gimao_module existait déjà en BDD ──────────────────────────────────
        # On met à jour l'état interne de Django sans recréer la table.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Module',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(help_text='Code court du module (ex: di, bt, eq)', max_length=20, unique=True)),
                        ('nom', models.CharField(help_text="Nom lisible du module (ex: Demandes d'intervention)", max_length=100)),
                    ],
                    options={
                        'verbose_name': 'Module',
                        'verbose_name_plural': 'Modules',
                        'db_table': 'gimao_module',
                        'ordering': ['nom'],
                    },
                ),
            ],
            database_operations=[
                # IF NOT EXISTS : no-op si la table existe déjà (ancienne BDD),
                # crée la table sur une nouvelle BDD.
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS gimao_module (
                            id   BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
                            code VARCHAR(20)  NOT NULL UNIQUE,
                            nom  VARCHAR(100) NOT NULL
                        )
                    """,
                    reverse_sql="DROP TABLE IF EXISTS gimao_module",
                ),
            ],
        ),

        # ── Nouveaux index sur Log (jamais créés) ───────────────────────────────
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-date'], name='log_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['utilisateur', '-date'], name='log_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['nomTable', '-date'], name='log_table_date_idx'),
        ),

        # ── Index sur Role et Utilisateur — IF NOT EXISTS (peuvent déjà exister) ──
        migrations.RunSQL(
            sql=[
                "CREATE INDEX IF NOT EXISTS role_nom_idx ON gimao_role (nomRole)",
                "CREATE INDEX IF NOT EXISTS user_name_list_idx ON gimao_utilisateur (nomFamille, prenom, id)",
                "CREATE INDEX IF NOT EXISTS user_role_list_idx ON gimao_utilisateur (role_id, nomFamille, prenom, id)",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS role_nom_idx ON gimao_role",
                "DROP INDEX IF EXISTS user_name_list_idx ON gimao_utilisateur",
                "DROP INDEX IF EXISTS user_role_list_idx ON gimao_utilisateur",
            ],
        ),
        # Synchroniser uniquement l'état Django pour ces index
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='role',
                    index=models.Index(fields=['nomRole'], name='role_nom_idx'),
                ),
                migrations.AddIndex(
                    model_name='utilisateur',
                    index=models.Index(fields=['nomFamille', 'prenom', 'id'], name='user_name_list_idx'),
                ),
                migrations.AddIndex(
                    model_name='utilisateur',
                    index=models.Index(fields=['role', 'nomFamille', 'prenom', 'id'], name='user_role_list_idx'),
                ),
            ],
            database_operations=[],  # déjà gérés par le RunSQL IF NOT EXISTS ci-dessus
        ),

        # ── FK permission.module — ajout conditionnel via RunPython ─────────────
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='permission',
                    name='module',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Module auquel appartient cette permission',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='permissions',
                        to='utilisateur.module',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_module_fk_if_missing,
                    reverse_code=remove_module_fk,
                ),
            ],
        ),
    ]
