# Generated by Django 4.2.29 on 2026-06-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_log_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='estDefaut',
            field=models.BooleanField(default=False, help_text='Rôle par défaut non supprimable'),
        ),
    ]
