# Generated by Django 4.2.29 on 2026-06-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnees', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fabricant',
            index=models.Index(fields=['nom'], name='fabricant_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['nom'], name='fournisseur_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=models.Index(fields=['nomLieu'], name='lieu_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='typedocument',
            index=models.Index(fields=['nomTypeDocument'], name='typedoc_nom_idx'),
        ),
    ]
