# Generated by Django 4.2.29 on 2026-03-03 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
        ('stock', '0001_initial'),
        ('donnees', '0001_initial'),
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('CORRECTIF', 'Correctif'), ('PREVENTIF', 'Préventif')], max_length=50)),
                ('date_assignation', models.DateTimeField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_prevue', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('EN_RETARD', 'En retard'), ('CLOTURE', 'Clôturé')], default='EN_ATTENTE', max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('commentaire_refus_cloture', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bon de travail',
                'verbose_name_plural': 'Bons de travail',
                'db_table': 'gimao_bon_travail',
            },
        ),
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('TRANSFORMEE', 'Transformée')], max_length=50)),
                ('date_creation', models.DateTimeField()),
                ('date_changementStatut', models.DateTimeField()),
            ],
            options={
                'verbose_name': "Demande d'intervention",
                'verbose_name_plural': "Demandes d'intervention",
                'db_table': 'gimao_demande_intervention',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PlanMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('necessiteHabilitationElectrique', models.BooleanField(default=False, help_text='Nécessite une habilitation électrique')),
                ('necessitePermisFeu', models.BooleanField(default=False, help_text='Nécessite un permis feu')),
            ],
            options={
                'verbose_name': 'Plan de maintenance',
                'verbose_name_plural': 'Plans de maintenance',
                'db_table': 'gimao_plan_maintenance',
            },
        ),
        migrations.CreateModel(
            name='TypePlanMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Type de plan de maintenance',
                'verbose_name_plural': 'Types de plan de maintenance',
                'db_table': 'gimao_type_plan_maintenance',
            },
        ),
        migrations.CreateModel(
            name='PlanMaintenanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donnees.document')),
                ('plan_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.planmaintenance')),
            ],
            options={
                'verbose_name': 'Document de plan de maintenance',
                'verbose_name_plural': 'Documents de plans de maintenance',
                'db_table': 'gimao_plan_maintenance_document',
                'unique_together': {('plan_maintenance', 'document')},
            },
        ),
        migrations.CreateModel(
            name='PlanMaintenanceConsommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_necessaire', models.IntegerField(default=1, help_text='Quantité nécessaire pour ce plan', validators=[django.core.validators.MinValueValidator(1)])),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.consommable')),
                ('plan_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.planmaintenance')),
            ],
            options={
                'verbose_name': 'Consommable nécessaire',
                'verbose_name_plural': 'Consommables nécessaires',
                'db_table': 'gimao_plan_maintenance_consommable',
                'unique_together': {('plan_maintenance', 'consommable')},
            },
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='consommables',
            field=models.ManyToManyField(blank=True, related_name='plans_maintenance', through='maintenance.PlanMaintenanceConsommable', to='stock.consommable'),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='plans_maintenance', through='maintenance.PlanMaintenanceDocument', to='donnees.document'),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_maintenance', to='equipement.equipement'),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='type_plan_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_maintenance', to='maintenance.typeplanmaintenance'),
        ),
        migrations.CreateModel(
            name='DemandeInterventionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande_intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.demandeintervention')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donnees.document')),
            ],
            options={
                'verbose_name': "Document de demande d'intervention",
                'verbose_name_plural': "Documents de demandes d'intervention",
                'db_table': 'gimao_demande_intervention_document',
                'unique_together': {('demande_intervention', 'document')},
            },
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='demandes_intervention', through='maintenance.DemandeInterventionDocument', to='donnees.document'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_intervention', to='equipement.equipement'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_intervention', to='utilisateur.utilisateur'),
        ),
        migrations.CreateModel(
            name='BonTravailDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.bontravail')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donnees.document')),
            ],
            options={
                'verbose_name': 'Document de bon de travail',
                'verbose_name_plural': 'Documents de bons de travail',
                'db_table': 'gimao_bon_travail_document',
                'unique_together': {('bon_travail', 'document')},
            },
        ),
        migrations.CreateModel(
            name='BonTravailConsommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.IntegerField(default=0, help_text='Quantité utilisée pour ce bon', validators=[django.core.validators.MinValueValidator(0)])),
                ('bon_travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.bontravail')),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.consommable')),
            ],
            options={
                'verbose_name': 'Consommable utilisé',
                'verbose_name_plural': 'Consommables utilisés',
                'db_table': 'gimao_bon_travail_consommable',
                'unique_together': {('bon_travail', 'consommable')},
            },
        ),
        migrations.AddField(
            model_name='bontravail',
            name='consommables',
            field=models.ManyToManyField(blank=True, related_name='bons_travail', through='maintenance.BonTravailConsommable', to='stock.consommable'),
        ),
        migrations.AddField(
            model_name='bontravail',
            name='demande_intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_travail', to='maintenance.demandeintervention'),
        ),
        migrations.AddField(
            model_name='bontravail',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='bons_travail', through='maintenance.BonTravailDocument', to='donnees.document'),
        ),
        migrations.AddField(
            model_name='bontravail',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_travail_responsable', to='utilisateur.utilisateur'),
        ),
        migrations.AddField(
            model_name='bontravail',
            name='utilisateur_assigne',
            field=models.ManyToManyField(blank=True, related_name='bons_travail_assignes', to='utilisateur.utilisateur'),
        ),
    ]
