# Generated by Django 4.2.29 on 2026-03-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bontravail',
            name='date_recuperation',
            field=models.DateTimeField(blank=True, help_text='Date a laquelle les pieces ont ete recuperees', null=True),
        ),
        migrations.AddField(
            model_name='bontravail',
            name='pieces_recuperees',
            field=models.BooleanField(default=False, help_text='Indique si toutes les pieces ont ete recuperees pour ce BT'),
        ),
        migrations.AddField(
            model_name='bontravailconsommable',
            name='date_confirme',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le consommable a été distribué', null=True),
        ),
        migrations.AddField(
            model_name='bontravailconsommable',
            name='estConfirme',
            field=models.BooleanField(default=False, help_text='Indique si le consommable a été donné'),
        ),
        migrations.AddField(
            model_name='bontravailconsommable',
            name='magasin_reserve',
            field=models.ForeignKey(blank=True, help_text='Magasin d ou le consommable a ete mis de cote', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.magasin'),
        ),
    ]
