# Generated by Django 4.2.29 on 2026-03-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_bontravail_date_recuperation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bontravail',
            name='archive',
            field=models.BooleanField(default=False, help_text="Indique si l'élément est archivé"),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='archive',
            field=models.BooleanField(default=False, help_text="Indique si l'élément est archivé"),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='statut_suppose',
            field=models.CharField(choices=[('EN_FONCTIONNEMENT', 'En fonctionnement'), ('DEGRADE', 'Dégradé'), ('A_LARRET', "A l'arrêt"), ('HORS_SERVICE', 'Hors service')], default='EN_FONCTIONNEMENT', max_length=50),
        ),
    ]
