# Generated by Django 4.2.29 on 2026-03-25 10:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_consommable_archive_magasin_archive'),
        ('maintenance', '0003_bontravail_archive_demandeintervention_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bontravail',
            name='duree_previsionnelle',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BonTravailConsommableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(help_text='Quantite reservee dans ce magasin pour ce consommable', validators=[django.core.validators.MinValueValidator(1)])),
                ('bon_travail_consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='maintenance.bontravailconsommable')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_bt', to='stock.magasin')),
            ],
            options={
                'verbose_name': 'Reservation de consommable',
                'verbose_name_plural': 'Reservations de consommables',
                'db_table': 'gimao_bon_travail_consommable_reservation',
                'unique_together': {('bon_travail_consommable', 'magasin')},
            },
        ),
    ]
