# Generated by Django 4.2.29 on 2026-06-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_bontravail_duree_previsionnelle_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bontravail',
            index=models.Index(fields=['archive', 'date_assignation', 'id'], name='bt_arch_assign_idx'),
        ),
        migrations.AddIndex(
            model_name='bontravail',
            index=models.Index(fields=['archive', 'statut', 'date_assignation', 'id'], name='bt_arch_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='bontravailconsommable',
            index=models.Index(fields=['bon_travail', 'estConfirme'], name='bt_conso_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeintervention',
            index=models.Index(fields=['archive', 'date_creation', 'id'], name='di_arch_date_id_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeintervention',
            index=models.Index(fields=['archive', 'equipement', 'date_creation', 'id'], name='di_arch_eq_date_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeintervention',
            index=models.Index(fields=['archive', 'utilisateur', 'date_creation', 'id'], name='di_arch_user_date_idx'),
        ),
    ]
