# Generated by Django 4.2.29 on 2026-03-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='archive',
            field=models.BooleanField(default=False, help_text="Indique si l'élément est archivé"),
        ),
    ]
