# Generated by Django 4.2.29 on 2026-06-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0003_equipement_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='declencher',
            name='anticipationJours',
            field=models.IntegerField(blank=True, default=None, help_text="Nombre de jours d'anticipation avant l'échéance (calendaire uniquement)", null=True),
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['archive', 'designation', 'id'], name='eq_arch_des_id_idx'),
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['archive', 'lieu', 'id'], name='eq_arch_lieu_id_idx'),
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['archive', 'modele', 'id'], name='eq_arch_mod_id_idx'),
        ),
        migrations.AddIndex(
            model_name='familleequipement',
            index=models.Index(fields=['nom'], name='famille_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='modeleequipement',
            index=models.Index(fields=['nom'], name='modele_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='statutequipement',
            index=models.Index(fields=['equipement', '-dateChangement'], name='eq_statut_last_idx'),
        ),
    ]
