# Generated by Django 4.2.29 on 2026-06-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0004_add_anticipation_jours_to_declencher'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='type',
            field=models.CharField(blank=True, choices=[('PEDAGOGIQUE', 'Pédagogique'), ('INFRASTRUCTURE', 'Infrastructure'), ('MECANIQUE', 'Mécanique'), ('ELECTRIQUE', 'Électrique'), ('HYDRAULIQUE', 'Hydraulique'), ('PLURITECHNIQUE', 'Pluritechnique')], help_text="Type d'équipement", max_length=20, null=True),
        ),
    ]
